version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data # Persists data between container restarts
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  node_server:
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:5000"
    volumes:
      - ./src:/app/src
      - /app/node_modules